import { toPng } from 'html-to-image'
import { getNodesBounds, getViewportForBounds } from '@xyflow/react'
import { jsPDF } from 'jspdf'
import type { VsmNode, VsmStateMap, VsmMetrics, TimeUnit } from '../types'
import { humanizeDuration } from './units'

const IMG_W = 1600
const IMG_H = 1000

/** Render the given map's nodes to a PNG data URL (fits the whole graph). */
export async function mapToPng(nodes: VsmNode[]): Promise<string> {
  const viewportEl = document.querySelector('.react-flow__viewport') as HTMLElement | null
  if (!viewportEl) throw new Error('Canvas not found')

  if (nodes.length === 0) {
    // produce a blank canvas rather than throwing
    const c = document.createElement('canvas')
    c.width = IMG_W
    c.height = IMG_H
    const ctx = c.getContext('2d')!
    ctx.fillStyle = '#f8fafc'
    ctx.fillRect(0, 0, IMG_W, IMG_H)
    return c.toDataURL('image/png')
  }

  const bounds = getNodesBounds(nodes)
  const vp = getViewportForBounds(bounds, IMG_W, IMG_H, 0.3, 2, 0.12)

  return toPng(viewportEl, {
    backgroundColor: '#f8fafc',
    width: IMG_W,
    height: IMG_H,
    style: {
      width: `${IMG_W}px`,
      height: `${IMG_H}px`,
      transform: `translate(${vp.x}px, ${vp.y}px) scale(${vp.zoom})`,
    },
    pixelRatio: 2,
    filter: (el) =>
      !(el.classList?.contains('react-flow__minimap') || el.classList?.contains('react-flow__controls')),
  })
}

export function downloadDataUrl(dataUrl: string, filename: string) {
  const a = document.createElement('a')
  a.href = dataUrl
  a.download = filename
  a.click()
}

/** Export the active map to a PNG file. */
export async function exportPng(state: VsmStateMap) {
  const url = await mapToPng(state.nodes)
  downloadDataUrl(url, `${safe(state.name)}.png`)
}

/** Export the active map to a PDF, fitting the image and appending a metrics block. */
export async function exportPdf(state: VsmStateMap, metrics: VsmMetrics, unit: TimeUnit) {
  const png = await mapToPng(state.nodes)
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' })
  const pw = pdf.internal.pageSize.getWidth()
  const ph = pdf.internal.pageSize.getHeight()
  const margin = 28

  pdf.setFontSize(16)
  pdf.setTextColor(15, 23, 42)
  pdf.text(`Value Stream Map — ${state.name}`, margin, margin + 4)

  // fit the map image under the title, leaving room for the metrics strip
  const imgTop = margin + 16
  const metricsH = 70
  const maxW = pw - margin * 2
  const maxH = ph - imgTop - metricsH - margin
  const ratio = Math.min(maxW / IMG_W, maxH / IMG_H)
  const w = IMG_W * ratio
  const h = IMG_H * ratio
  pdf.addImage(png, 'PNG', margin + (maxW - w) / 2, imgTop, w, h, undefined, 'FAST')

  // metrics strip
  const my = imgTop + h + 18
  pdf.setDrawColor(203, 213, 225)
  pdf.line(margin, my - 10, pw - margin, my - 10)
  pdf.setFontSize(10)
  const items: [string, string][] = [
    ['Lead Time', humanizeDuration(metrics.leadTime)],
    ['VA Time', humanizeDuration(metrics.valueAddedTime)],
    ['NVA Time', humanizeDuration(metrics.nonValueAddedTime)],
    ['VA Ratio (PCE)', `${metrics.vaRatio.toFixed(2)}%`],
    ['Process Steps', String(metrics.processCount)],
    ['Inventory Pts', String(metrics.inventoryCount)],
  ]
  const colW = (pw - margin * 2) / items.length
  items.forEach(([label, value], i) => {
    const x = margin + i * colW
    pdf.setTextColor(100, 116, 139)
    pdf.text(label.toUpperCase(), x, my)
    pdf.setTextColor(15, 23, 42)
    pdf.setFontSize(13)
    pdf.text(value, x, my + 16)
    pdf.setFontSize(10)
  })
  pdf.setTextColor(148, 163, 184)
  pdf.setFontSize(8)
  pdf.text(`Time unit: ${unit} · Generated by VSM Studio`, margin, ph - 14)

  pdf.save(`${safe(state.name)}.pdf`)
}

function safe(name: string) {
  return name.replace(/[^a-z0-9-_]+/gi, '_').toLowerCase() || 'vsm'
}
